language: go

go:
  - 1.13.1

env:
  - GO111MODULE=off

before_install:
  - go get -v github.com/gorilla/mux
  - go get -v github.com/gorilla/websocket
  - go get -v go.mongodb.org/mongo-driver/bson
  - go get -v go.mongodb.org/mongo-driver/bson/primitive
  - go get -v go.mongodb.org/mongo-driver/mongo
  - go get -v go.mongodb.org/mongo-driver/mongo/options
  - go get -v go.mongodb.org/mongo-driver/mongo/readpref
  - go get -v github.com/creekorful/microgo/pkg/httputil

script:
  - go build -v api.go handler.go service.go